name: Checks
on:
    pull_request:
    push:
        branches:
            - "master"
            - "v[0-9]"
jobs:
    checks:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            -
                name: Checkout code
                uses: actions/checkout@v2
            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
            -
                name: Install dependencies
                run: composer install --no-progress --prefer-dist --no-interaction

            -
                name: Install extra tools
                run: |
                    wget -q https://github.com/composer-unused/composer-unused/releases/latest/download/composer-unused.phar
                    wget -q https://github.com/maglnet/ComposerRequireChecker/releases/download/4.5.0/composer-require-checker.phar

            -
                name: Run checks
                run: composer check

            -
                name: Check unused dependencies
                run: php composer-unused.phar --output-format=default

            -
                name: Check shadow dependencies
                run: php composer-require-checker.phar check composer.json


    tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-version: [ '7.4', '8.0', '8.1', '8.2' ]
                dependency-version: [ prefer-lowest, prefer-stable ]
        steps:
            -
                name: Checkout code
                uses: actions/checkout@v2
            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
            -
                name: Update dependencies
                run: composer update --no-progress --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

            -
                name: Run tests
                run: composer check:tests
